service:
  name: sls-ts

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello-callback:
    handler: handler-callback.helloCallback
    events:
      - http:
          method: get
          path: hello-callback
          integration: lambda
  hello-async:
    handler: handler-async.helloAsync
    events:
      - http:
          method: get
          path: hello-async
          integration: lambda
